In [1]:
pip install gwaslab

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gwaslab in /home/icog-bioai/.local/lib/python3.10/site-packages (3.5.5)
Requirement already satisfied: pandas!=1.5,>=1.3 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (2.2.2)
Requirement already satisfied: numpy<2,>=1.21.2 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (1.26.0)
Requirement already satisfied: matplotlib<3.9,>=3.8 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (3.8.4)
Requirement already satisfied: seaborn>=0.12 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (0.13.2)
Requirement already satisfied: scipy>=1.12 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (1.14.0)
Requirement already satisfied: pySAM==0.22.1 in /usr/local/lib/python3.10/dist-packages (from gwaslab) (0.22.1)
Requirement already satisfied: Biopython>=1.79 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (1.84)
Requirement already satisfied: adjustText<=0.8,>=0.7.3 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (0.8)
Requirement already satisfied: liftover<=1.3.1,>=1.1.13 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (1.3.1)
Requirement already satisfied: scikit-allel>=1.3.5 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (1.3.13)
Requirement already satisfied: pyensembl==2.2.3 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (2.2.3)
Requirement already satisfied: gtfparse==1.3.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from gwaslab) (1.3.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from gwaslab) (3.11.0)
Requirement already satisfied: typechecks>=0.0.2 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pyensembl==2.2.3->gwaslab) (0.1.0)
Requirement already satisfied: datacache>=1.1.4 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pyensembl==2.2.3->gwaslab) (1.4.1)
Requirement already satisfied: memoized-property>=1.0.2 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pyensembl==2.2.3->gwaslab) (1.0.3)
Requirement already satisfied: tinytimer in /home/icog-bioai/.local/lib/python3.10/site-packages (from pyensembl==2.2.3->gwaslab) (0.0.0)
Requirement already satisfied: serializable in /home/icog-bioai/.local/lib/python3.10/site-packages (from pyensembl==2.2.3->gwaslab) (0.4.1)
Requirement already satisfied: nose>=1.3.3 in /usr/lib/python3/dist-packages (from pyensembl==2.2.3->gwaslab) (1.3.7)
Requirement already satisfied: pylint>=1.4.4 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pyensembl==2.2.3->gwaslab) (3.3.3)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from liftover<=1.3.1,>=1.1.13->gwaslab) (1.26.5)
Requirement already satisfied: contourpy>=1.0.1 in /home/icog-bioai/.local/lib/python3.10/site-packages (from matplotlib<3.9,>=3.8->gwaslab) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /home/icog-bioai/.local/lib/python3.10/site-packages (from matplotlib<3.9,>=3.8->gwaslab) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from matplotlib<3.9,>=3.8->gwaslab) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/icog-bioai/.local/lib/python3.10/site-packages (from matplotlib<3.9,>=3.8->gwaslab) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.8->gwaslab) (23.1)
Requirement already satisfied: pillow>=8 in /usr/lib/python3/dist-packages (from matplotlib<3.9,>=3.8->gwaslab) (9.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.8->gwaslab) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.8->gwaslab) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas!=1.5,>=1.3->gwaslab) (2022.1)
Requirement already satisfied: tzdata>=2022.7 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pandas!=1.5,>=1.3->gwaslab) (2024.1)
Requirement already satisfied: dask[array] in /home/icog-bioai/.local/lib/python3.10/site-packages (from scikit-allel>=1.3.5->gwaslab) (2024.12.1)
Requirement already satisfied: appdirs>=1.4.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (1.4.4)
Requirement already satisfied: progressbar33>=2.4 in /home/icog-bioai/.local/lib/python3.10/site-packages (from datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (2.4)
Requirement already satisfied: requests>=2.5.1 in /home/icog-bioai/.local/lib/python3.10/site-packages (from datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (2.32.3)
Requirement already satisfied: mock in /home/icog-bioai/.local/lib/python3.10/site-packages (from datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (5.1.0)
Requirement already satisfied: dill>=0.2 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (0.3.8)
Requirement already satisfied: platformdirs>=2.2.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (4.2.2)
Requirement already satisfied: astroid<=3.4.0-dev0,>=3.3.8 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (3.3.8)
Requirement already satisfied: isort!=5.13.0,<6,>=4.2.5 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (5.13.2)
Requirement already satisfied: mccabe<0.8,>=0.6 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (0.7.0)
Requirement already satisfied: tomli>=1.1.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (2.0.1)
Requirement already satisfied: tomlkit>=0.10.1 in /home/icog-bioai/.local/lib/python3.10/site-packages (from pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (0.12.5)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib<3.9,>=3.8->gwaslab) (1.16.0)
Requirement already satisfied: click>=8.1 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (8.1.7)
Requirement already satisfied: cloudpickle>=3.0.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (3.0.0)
Requirement already satisfied: fsspec>=2021.09.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (2024.12.0)
Requirement already satisfied: partd>=1.4.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (1.0.0)
Requirement already satisfied: importlib_metadata>=4.13.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from dask[array]->scikit-allel>=1.3.5->gwaslab) (7.1.0)
Requirement already satisfied: simplejson in /home/icog-bioai/.local/lib/python3.10/site-packages (from serializable->pyensembl==2.2.3->gwaslab) (3.19.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/icog-bioai/.local/lib/python3.10/site-packages (from astroid<=3.4.0-dev0,>=3.3.8->pylint>=1.4.4->pyensembl==2.2.3->gwaslab) (4.12.2)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib_metadata>=4.13.0->dask[array]->scikit-allel>=1.3.5->gwaslab) (1.0.0)
Requirement already satisfied: locket in /home/icog-bioai/.local/lib/python3.10/site-packages (from partd>=1.4.0->dask[array]->scikit-allel>=1.3.5->gwaslab) (1.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.1->datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.5.1->datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.5.1->datacache>=1.1.4->pyensembl==2.2.3->gwaslab) (2020.6.20)

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import gwaslab as gl
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import gzip

In [51]:
file_path = "../../data/susie/gwas/21001_raw.gwas.imputed_v3.both_sexes.tsv.bgz"
with gzip.open(file_path, 'rt') as f:
    gwas_data_df = pd.read_csv(f, sep='\t')

In [53]:
gwas_data_df.head()
chr16_df = gwas_data_df[gwas_data_df['variant'].str.startswith('16:')]

chr16_df.head()
chr16_df.to_csv("../../data/susie/gwas/chr_16_row.csv", index=False)

split_variant = chr16_df['variant'].str.split(':', expand=True)
chr16_df['CHR'] = split_variant[0]
chr16_df['POS'] = split_variant[1]
chr16_df['A2'] = split_variant[2]
chr16_df['A1'] = split_variant[3]
chr16_df.head()
chr16_df = chr16_df[~chr16_df["low_confidence_variant"]]
chr16_df = chr16_df[chr16_df["minor_AF"] > 0.01]
chr16_df = chr16_df.dropna(subset=["A1", "A2"])
# chr16_df["SNPID"].to_csv("../../data/susie/gwas/chr_16_formatted_SNPs.txt", index=False)

/tmp/ipykernel_1673061/1360153638.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chr16_df['CHR'] = split_variant[0]
/tmp/ipykernel_1673061/1360153638.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chr16_df['POS'] = split_variant[1]
/tmp/ipykernel_1673061/1360153638.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chr16_df['A2'] = split_variant[2]
/tmp/ipykernel_1673061/1360153638.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  chr16_df['A1'] = split_variant[3]

In [54]:
chr16_df.head()

,variant,minor_allele,minor_AF,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,pval,CHR,POS,A2,A1
11246842,16:81639:C:A,C,0.176406,False,359983,592960.0,16238300.0,-0.011685,0.015499,-0.753933,0.450890,16,81639,C,A
11246843,16:83520:T:C,C,0.144018,False,359983,103688.0,2838220.0,-0.018358,0.016387,-1.120300,0.262588,16,83520,T,C
11246844,16:83626:G:A,A,0.196276,False,359983,141312.0,3869320.0,-0.005061,0.014658,-0.345267,0.729894,16,83626,G,A
11246845,16:83629:C:A,A,0.213709,False,359983,153863.0,4212840.0,-0.006793,0.013819,-0.491546,0.623041,16,83629,C,A
11246846,16:83802:G:A,A,0.067999,False,359983,48956.9,1341000.0,0.009576,0.022340,0.428629,0.668194,16,83802,G,A

In [62]:
chr16_df=chr16_df.rename(columns={'SNP':'SNPID', 'pval':'P'})
chr16_df["SNPID"].to_csv("../../data/susie/gwas/chr_16_formatted_SNPs.txt", index=False)

In [73]:
chr16_df=chr16_df.rename(columns={'SNP':'SNPID', 'pval':'P'})
chr16_df.head()

,SNPID,minor_allele,minor_AF,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,P,CHR,POS,A2,A1
11246842,16:81639:C:A,C,0.176406,False,359983,592960.0,16238300.0,-0.011685,0.015499,-0.753933,0.450890,16,81639,C,A
11246843,16:83520:T:C,C,0.144018,False,359983,103688.0,2838220.0,-0.018358,0.016387,-1.120300,0.262588,16,83520,T,C
11246844,16:83626:G:A,A,0.196276,False,359983,141312.0,3869320.0,-0.005061,0.014658,-0.345267,0.729894,16,83626,G,A
11246845,16:83629:C:A,A,0.213709,False,359983,153863.0,4212840.0,-0.006793,0.013819,-0.491546,0.623041,16,83629,C,A
11246846,16:83802:G:A,A,0.067999,False,359983,48956.9,1341000.0,0.009576,0.022340,0.428629,0.668194,16,83802,G,A

In [ ]:
chr16_df["SNPID"].to_csv("../../data/susie/gwas/chr_16_formatted_SNPs.txt", index=False)

In [75]:
chr16_df.head()

,SNPID,minor_allele,minor_AF,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,P,CHR,POS,A2,A1
11246842,16:81639:C:A,C,0.176406,False,359983,592960.0,16238300.0,-0.011685,0.015499,-0.753933,0.450890,16,81639,C,A
11246843,16:83520:T:C,C,0.144018,False,359983,103688.0,2838220.0,-0.018358,0.016387,-1.120300,0.262588,16,83520,T,C
11246844,16:83626:G:A,A,0.196276,False,359983,141312.0,3869320.0,-0.005061,0.014658,-0.345267,0.729894,16,83626,G,A
11246845,16:83629:C:A,A,0.213709,False,359983,153863.0,4212840.0,-0.006793,0.013819,-0.491546,0.623041,16,83629,C,A
11246846,16:83802:G:A,A,0.067999,False,359983,48956.9,1341000.0,0.009576,0.022340,0.428629,0.668194,16,83802,G,A

In [74]:
chr16_df.to_csv("../../data/susie/gwas/chr_16_ready_for_harmo.csv", index=False)

In [67]:

ref_bim = pd.read_csv(
    "../../data/susie/test_plink/plink_binary/chr16_eur.bim", 
    sep="\t", 
    header=None, 
    names=["CHR", "SNP", "CM", "POS", "A1", "A2"]
)


ref_bim["CHR"] = ref_bim["CHR"].astype(str)  
ref_bim["POS"] = ref_bim["POS"].astype(int)   

chr16_df["CHR"] = chr16_df["CHR"].astype(str)  
chr16_df["POS"] = chr16_df["POS"].astype(int)  


merged = pd.merge(
    chr16_df,
    ref_bim,
    on=["CHR", "POS"],
    suffixes=("_gwas", "_ref")
)


mismatch = (
    (merged["A1_gwas"] != merged["A1_ref"]) |
    (merged["A2_gwas"] != merged["A2_ref"])
)
print(f"Found {mismatch.sum()} allele mismatches.")

Found 57070 allele mismatches.

In [68]:
mismatch.head(20)

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [69]:
swapped_mismatch = (
    (merged["A1_gwas"] == merged["A2_ref"]) & 
    (merged["A2_gwas"] == merged["A1_ref"])
)
print(f"Simple allele swaps: {swapped_mismatch.sum()}")

Simple allele swaps: 55055

In [70]:
complement = {'A':'T', 'T':'A', 'C':'G', 'G':'C', 'D':'D', 'I':'I'}

flipped_mismatch = (
    (merged["A1_gwas"].map(complement) == merged["A1_ref"]) & 
    (merged["A2_gwas"].map(complement) == merged["A2_ref"])
)
print(f"Strand flipped SNPs: {flipped_mismatch.sum()}")

Strand flipped SNPs: 8996

In [71]:
def harmonize_alleles(row):
    if row["A1_gwas"] == row["A1_ref"] and row["A2_gwas"] == row["A2_ref"]:
        return 1, row["beta"]
    elif row["A1_gwas"] == row["A2_ref"] and row["A2_gwas"] == row["A1_ref"]:
        return 1, -row["beta"] 
    
    elif (complement.get(row["A1_gwas"], '') == row["A1_ref"] and 
          complement.get(row["A2_gwas"], '') == row["A2_ref"]):
        return 1, row["beta"]  
    
    elif (complement.get(row["A1_gwas"], '') == row["A2_ref"] and 
          complement.get(row["A2_gwas"], '') == row["A1_ref"]):
        return 1, -row["beta"]  
    
    else:
        return 0, np.nan  

merged[["keep", "harmonized_beta"]] = merged.apply(harmonize_alleles, axis=1, result_type="expand")

print(f"Successfully harmonized: {merged['keep'].sum()}")
print(f"Remaining mismatches: {len(merged) - merged['keep'].sum()}")

Successfully harmonized: 282186.0
Remaining mismatches: 2015.0

In [76]:
merged.head()

,SNP_gwas,minor_allele,minor_AF,low_confidence_variant,n_complete_samples,AC,ytx,beta,se,tstat,...,CHR,POS,A2_gwas,A1_gwas,SNP_ref,CM,A1_ref,A2_ref,keep,harmonized_beta
0,16:81639:C:A,C,0.176406,False,359983,592960.0,16238300.0,-0.011685,0.015499,-0.753933,...,16,81639,C,A,16:81639:C:A,0,C,A,1.0,0.011685
1,16:83520:T:C,C,0.144018,False,359983,103688.0,2838220.0,-0.018358,0.016387,-1.120300,...,16,83520,T,C,16:83520:T:C,0,C,T,1.0,-0.018358
2,16:83626:G:A,A,0.196276,False,359983,141312.0,3869320.0,-0.005061,0.014658,-0.345267,...,16,83626,G,A,16:83626:G:A,0,A,G,1.0,-0.005061
3,16:83629:C:A,A,0.213709,False,359983,153863.0,4212840.0,-0.006793,0.013819,-0.491546,...,16,83629,C,A,16:83629:C:A,0,A,C,1.0,-0.006793
4,16:83802:G:A,A,0.067999,False,359983,48956.9,1341000.0,0.009576,0.022340,0.428629,...,16,83802,G,A,16:83802:G:A,0,A,G,1.0,0.009576

In [81]:
harmonized_df = merged[merged["keep"] == 1].copy()
output_cols = ["CHR", "POS", "A1_ref", "A2_ref", "harmonized_beta", "se", "P", "SNP_ref"]
harmonized_df = harmonized_df[output_cols]

harmonized_df.columns = ["CHR", "POS", "A1", "A2", "beta", "se", "pval", "SNP_ref"]

harmonized_df.to_csv("../../data/susie/test_plink/harmonized_gwas_data.csv", index=False)

In [ ]:
harmonized_df=harmonized_df.rename(columns={'SNP_ref':'SNPID'})
harmonized_df.head()

  CHR    POS A1 A2      beta        se      pval         SNPID
0  16  81639  C  A  0.011685  0.015499  0.450890  16:81639:C:A
1  16  83520  C  T -0.018358  0.016387  0.262588  16:83520:T:C
2  16  83626  A  G -0.005061  0.014658  0.729894  16:83626:G:A
3  16  83629  A  C -0.006793  0.013819  0.623041  16:83629:C:A
4  16  83802  A  G  0.009576  0.022340  0.668194  16:83802:G:A

In [84]:
harmonized_df["SNPID"].to_csv("../../data/susie/test_plink/harmonized_gwas_data_snps.txt", index=False)

In [85]:

print(f"Duplicate positions: {harmonized_df.duplicated(['CHR','POS']).sum()}")
print(harmonized_df["A1"].value_counts())
print(harmonized_df["A2"].value_counts())

Duplicate positions: 151
A1
A                  72258
T                  71939
G                  63243
C                  62916
CA                  1184
                   ...
GCCCGGCCCCGC           1
CAAGAG                 1
CCAGT                  1
AAATAAAAAAAAAAT        1
CACTTCCTAG             1
Name: count, Length: 1739, dtype: int64
A2
C                 79827
G                 77533
A                 56243
T                 54301
CT                 1127
                  ...
CTATTT                1
GACAAGTGACAATC        1
AACAAAC               1
CTCCTT                1
TTCAGATTCTTCTA        1
Name: count, Length: 2365, dtype: int64

In [86]:
problem_variants = merged[merged["keep"] == 0]
print(problem_variants["A1_gwas"].str.len().value_counts())
print(problem_variants["A2_gwas"].str.len().value_counts())

harmonized_df = harmonized_df[harmonized_df["A1"].str.len() == 1]
harmonized_df = harmonized_df[harmonized_df["A2"].str.len() == 1]

A1_gwas
1     1012
2      386
3      195
5      133
4       61
7       37
6       36
9       31
11      24
13      21
16      20
21      14
10      10
17       8
8        7
26       7
25       3
12       2
15       2
42       2
19       1
37       1
29       1
24       1
Name: count, dtype: int64
A2_gwas
1     1470
2      224
3       99
5       67
4       33
9       32
6       22
7       11
13      11
17       8
8        7
21       6
11       5
14       4
10       3
22       2
16       2
12       1
30       1
38       1
15       1
23       1
25       1
27       1
28       1
18       1
Name: count, dtype: int64

In [47]:
harmonized_df = harmonized_df.drop_duplicates(["CHR", "POS"], keep="first")

In [87]:
print("Final allele distributions:")
print(harmonized_df["A1"].value_counts())
print(harmonized_df["A2"].value_counts())

# harmonized_df["MAF"] = harmonized_df[["minor_AF"]].min(axis=1)
# print("MAF distribution:")
# print(harmonized_df["MAF"].describe())

Final allele distributions:
A1
T    68590
A    68552
G    60574
C    58361
Name: count, dtype: int64
A2
C    75866
G    75201
A    53394
T    51616
Name: count, dtype: int64

In [99]:
harmonized_df.head()

  CHR    POS A1 A2      beta        se      pval         SNPID
0  16  81639  C  A  0.011685  0.015499  0.450890  16:81639:C:A
1  16  83520  C  T -0.018358  0.016387  0.262588  16:83520:T:C
2  16  83626  A  G -0.005061  0.014658  0.729894  16:83626:G:A
3  16  83629  A  C -0.006793  0.013819  0.623041  16:83629:C:A
4  16  83802  A  G  0.009576  0.022340  0.668194  16:83802:G:A

In [89]:
harmonized_df[harmonized_df["POS"]==53828066]

       CHR       POS A1 A2      beta        se           pval            SNPID
135837  16  53828066  T  C  0.349002  0.011405  2.244600e-205  16:53828066:C:T

In [104]:
variant_position = 53828066
start_pos = variant_position - 500000
end_pos = variant_position + 500000

df_region = harmonized_df[
        (harmonized_df["CHR"] == "16") & 
        (harmonized_df["POS"] >= start_pos) & 
        (harmonized_df["POS"] <= end_pos)
    ]

In [107]:
df_region["SNPID"].to_csv("../../data/susie/test_plink/harmonized_gwas_data_region.txt", index=False)

In [108]:
!plink \
  --bfile "../../data/susie/test_plink/plink_binary/chr16_eur" \
  --keep-allele-order \
  --r square \
  --extract ../../data/susie/test_plink/harmonized_gwas_data_region.txt \
  --out ../../data/susie/test_plink/test_sig_locus_mt

PLINK v1.90b7.2 64-bit (11 Dec 2023)           www.cog-genomics.org/plink/1.9/
(C) 2005-2023 Shaun Purcell, Christopher Chang   GNU General Public License v3
Logging to ../../data/susie/test_plink/test_sig_locus_mt.log.
Options in effect:
  --bfile ../../data/susie/test_plink/plink_binary/chr16_eur
  --extract ../../data/susie/test_plink/harmonized_gwas_data_region.txt
  --keep-allele-order
  --out ../../data/susie/test_plink/test_sig_locus_mt
  --r square

257419 MB RAM detected; reserving 128709 MB for main workspace.

2697949 variants loaded from .bim file.
503 people (0 males, 0 females, 503 ambiguous) loaded from .fam.
Ambiguous sex IDs written to
../../data/susie/test_plink/test_sig_locus_mt.nosex .
--extract: 2954 variants remaining.
Using up to 27 threads (change this with --threads).
Before main variant filters, 503 founders and 0 nonfounders present.
Calculating allele frequencies... 10111213141516171819202122232425262728293031323334353637383940414243444546474849505152535455565758596061626364656667686970717273747576777879808182838485868788899091929394959697989 done.
Total genotyping rate is 0.999978.
2954 variants and 503 people pass filters and QC.
Note: No phenotypes present.
--r square to ../../data/susie/test_plink/test_sig_locus_mt.ld ...
0% [processingwriting]        done.

In [112]:
import rpy2
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
import rpy2.robjects.numpy2ri as numpy2ri
numpy2ri.activate()

In [113]:
susieR = importr('susieR')

In [109]:
ld_r = pd.read_csv("../../data/susie/test_plink/test_sig_locus_mt.ld", sep="\t", header=None)
R_df = ld_r.values

In [135]:
import rpy2.robjects as ro
ro.r('set.seed(123)')
fit = susieR.susie_rss(
    bhat = df_region["beta"].values.reshape(len(df_region), 1),
    shat =df_region["se"].values.reshape(len(df_region), 1),
    R = R_df,
    L = 1,
    n = 359983
)

credible_sets = susieR.susie_get_cs(fit, coverage=0.95, min_abs_corr=0.5, Xcorr=R_df)

In [136]:
credible_sets = susieR.susie_get_cs(fit, coverage=0.95, min_abs_corr=0.5, Xcorr=R_df)
print(credible_sets)

$cs
$cs$L1
[1] 1168 1173 1177 1178 1188


$purity
   min.abs.corr mean.abs.corr median.abs.corr
L1     0.992977     0.9971908               1

$cs_index
[1] 1

$coverage
[1] 0.9705779

$requested_coverage
[1] 0.95

In [ ]:
df_region.loc[:, "cs"] = 0

In [137]:

df_region.loc[:, "cs"] = 0
n_cs = len(susieR.susie_get_cs(fit, coverage = 0.95, min_abs_corr = 0.5, Xcorr = R_df)[0])
print(n_cs)
credible_sets = susieR.susie_get_cs(fit, coverage=0.95, min_abs_corr=0.5, Xcorr=R_df)[0]

for i in range(n_cs):
    cs_index = credible_sets[i]
    df_region.iloc[np.array(cs_index) - 1, df_region.columns.get_loc("cs")] = i + 1


df_region["pip"] = np.array(susieR.susie_get_pip(fit))

1

In [140]:
df_region = df_region.reset_index(drop=True)

In [141]:
cs_index = np.array(credible_sets[0])
for i in range(1, n_cs):
    cs_index = np.concatenate((cs_index, np.array(credible_sets[i])), axis=0)
credible_snps = df_region.loc[cs_index - 1, :]

print(credible_snps)

     CHR       POS A1 A2      beta        se           pval            SNPID  \
1167  16  53800954  C  T  0.359304  0.011353  1.569760e-219  16:53800954:T:C
1172  16  53802494  T  C  0.359699  0.011353  5.465200e-220  16:53802494:C:T
1176  16  53803223  A  G  0.359563  0.011354  8.107390e-220  16:53803223:G:A
1177  16  53803574  A  T  0.359554  0.011353  8.187040e-220  16:53803574:T:A
1187  16  53806453  G  A  0.359082  0.011349  2.114840e-219  16:53806453:A:G

      cs       pip
1167   1  0.114891
1172   1  0.328532
1176   1  0.221432
1177   1  0.219802
1187   1  0.085920

In [143]:
credible_snps_sorted = credible_snps.sort_values(by="pip", ascending=False)
print(credible_snps_sorted[["SNPID", "pip"]])

                SNPID       pip
1172  16:53802494:C:T  0.328532
1176  16:53803223:G:A  0.221432
1177  16:53803574:T:A  0.219802
1167  16:53800954:T:C  0.114891
1187  16:53806453:A:G  0.085920

In [144]:
import requests


chrom = credible_snps["CHR"]
pos = credible_snps["POS"]
pip = credible_snps["pip"]
crediable_snps_rs = []

def get_rsid(chrom, pos, genome="hg19"):
    url = f"https://api.genome.ucsc.edu/getData/track?genome={genome};track=dbSnp155;chrom=chr{chrom};start={pos-1};end={pos}"
    response = requests.get(url).json()
    if "dbSnp155" in response and response["dbSnp155"]:
        return response["dbSnp155"][0]["name"]
    return None

for c, p, pip in zip(chrom, pos, pip):
    rsid = get_rsid(c, p)
    crediable_snps_rs.append([rsid, c, p, pip])

df_crediable_snps= pd.DataFrame(crediable_snps_rs, columns=["rsID", "Chromosome", "Position", "pip"])
df_crediable_snps = df_crediable_snps.sort_values(by="pip", ascending=False)

In [145]:
df_crediable_snps

         rsID Chromosome  Position       pip
1  rs11642015         16  53802494  0.328532
2  rs62048402         16  53803223  0.221432
3   rs1558902         16  53803574  0.219802
0   rs1421085         16  53800954  0.114891
4  rs56094641         16  53806453  0.085920