In [ ]:
import pandas as pd
all_chr=pd.read_csv("../data/susie/cojo/all_chr/all_chr_cojo.jma.cojo", sep="\t")

In [20]:
chr16_all=all_chr[all_chr["Chr"]==16]

In [24]:
chr16_all.shape

(31, 14)

In [21]:
chr16_all

,Chr,SNP,bp,refA,freq,b,se,p,n,freq_geno,bJ,bJ_se,pJ,LD_r
399,16,16:407723:G:A,407723,A,0.355244,-0.080704,0.011714,5.593560e-12,356446,0.401757,-0.150325,0.013207,5.108150e-30,0.330416
400,16,16:3708567:G:A,3708567,A,0.314140,0.066784,0.012033,2.852600e-08,359132,0.504393,0.113434,0.013187,7.859760e-18,-0.239183
401,16,16:4015729:C:T,4015729,T,0.384448,0.116658,0.011499,3.501560e-24,357924,0.344050,0.140383,0.011967,8.847040e-32,0.189035
402,16,16:4932470:G:A,4932470,A,0.437222,-0.068619,0.011281,1.179990e-09,357796,0.411542,-0.113932,0.012528,9.495070e-20,0.082282
403,16,16:9714809:A:AAGAG,9714809,AAGAG,0.299455,-0.070539,0.012237,8.194340e-09,356630,0.302316,-0.074659,0.012379,1.629130e-09,0.000000
404,16,16:19926191:T:C,19926191,C,0.143032,-0.125751,0.015957,3.256410e-15,358927,0.052716,-0.117192,0.016100,3.359820e-13,0.128273
405,16,16:20371075:A:T,20371075,T,0.484929,-0.072876,0.011142,6.133070e-11,361262,0.334864,-0.062074,0.011246,3.394130e-08,0.024450
406,16,16:24562458:T:C,24562458,C,0.483824,-0.062082,0.011161,2.659930e-08,360127,0.665335,-0.121075,0.012163,2.405990e-23,0.086424
407,16,16:24811740:T:C,24811740,C,0.266977,-0.081349,0.012596,1.056980e-10,360831,0.239018,-0.092689,0.012788,4.216120e-13,0.000832
408,16,16:28857645:A:G,28857645,G,0.405474,0.129342,0.011357,4.752350e-30,360219,0.349241,0.138355,0.011402,6.961020e-34,-0.063094
409,16,16:29994922:C:T,29994922,T,0.484633,0.126127,0.011189,1.802030e-29,358168,0.367412,0.148511,0.011416,1.093160e-38,0.171922
410,16,16:31075175:G:A,31075175,A,0.373145,-0.124927,0.011521,2.143150e-27,360753,0.345847,-0.206706,0.012728,2.635370e-59,0.000000
411,16,16:53807005:AT:A,53807005,A,0.482868,0.299494,0.011184,5.744520e-158,357994,0.525559,0.540461,0.022845,9.770000e-124,-0.325312
412,16,16:53814470:C:T,53814470,T,0.129047,-0.118643,0.016640,1.003460e-12,359974,0.100240,0.477231,0.028581,1.369720e-62,-0.426052
413,16,16:53815161:T:G,53815161,G,0.491533,0.279766,0.011137,2.926380e-139,360819,0.603834,0.941394,0.031817,2.136310e-192,0.532698
414,16,16:53815706:CTGTT:C,53815706,C,0.099094,-0.148509,0.018711,2.070780e-15,358414,0.293131,-1.424780,0.047526,1.838350e-197,-0.241786
415,16,16:53823745:T:G,53823745,G,0.110497,-0.130443,0.018495,1.753490e-12,333193,0.215455,-0.919497,0.040029,9.100680e-117,-0.310053
416,16,16:53828066:C:T,53828066,T,0.392165,0.349002,0.011405,1.224550e-205,360397,0.221446,-0.481828,0.030674,1.336110e-55,0.821113
417,16,16:53830491:T:C,53830491,C,0.432609,0.313572,0.011237,2.348400e-171,360693,0.291334,-0.329204,0.024414,1.934000e-41,-0.306611
418,16,16:53835825:C:T,53835825,T,0.062992,-0.148968,0.022975,8.930430e-11,359585,0.194289,-1.180670,0.046834,3.145320e-140,0.285448
419,16,16:53839355:GT:G,53839355,G,0.405865,0.122079,0.012224,1.747790e-23,310819,0.531150,0.171988,0.014993,1.843490e-30,-0.200972
420,16,16:53864764:CG:C,53864764,C,0.322651,-0.081399,0.012050,1.425430e-11,353039,0.168930,-0.086096,0.012545,6.732250e-12,0.000000
421,16,16:64697880:C:T,64697880,T,0.142307,-0.089371,0.015943,2.076990e-08,361088,0.178714,-0.098352,0.016293,1.574230e-09,-0.094547
422,16,16:69144151:C:G,69144151,G,0.127241,0.094296,0.016732,1.744150e-08,360343,0.167532,0.105322,0.017135,7.906800e-10,-0.008063
423,16,16:69651866:C:T,69651866,T,0.409140,-0.106813,0.011354,5.071730e-21,359443,0.284944,-0.092882,0.011853,4.642230e-15,-0.209010
424,16,16:69955690:A:G,69955690,G,0.440290,0.080898,0.011247,6.354120e-13,359348,0.475639,0.090583,0.012067,6.067540e-14,0.047963
425,16,16:70514828:A:C,70514828,C,0.452027,0.079024,0.011236,2.017630e-12,358255,0.418530,0.078388,0.011298,3.976460e-12,-0.002181
426,16,16:72038659:C:T,72038659,T,0.322396,-0.069476,0.011944,5.996310e-09,359482,0.494010,-0.088867,0.012185,3.023600e-13,-0.013169
427,16,16:72996162:G:A,72996162,A,0.399635,-0.065649,0.011515,1.191530e-08,352121,0.268171,-0.072136,0.011689,6.771440e-10,-0.007967
428,16,16:73426890:C:T,73426890,T,0.081166,-0.112133,0.020547,4.828940e-08,355835,0.095447,-0.134106,0.020667,8.654350e-11,0.006360
429,16,16:76697625:A:G,76697625,G,0.186761,0.078618,0.014359,4.372660e-08,357751,0.218650,0.086071,0.014425,2.418190e-09,0.000000

In [ ]:
chr_16=pd.read_csv("../data/susie/cojo/chr16/chr16.jma.cojo", sep="\t")

In [25]:
chr_16.shape

(30, 14)

In [19]:
chr_16

,Chr,SNP,bp,refA,freq,b,se,p,n,freq_geno,bJ,bJ_se,pJ,LD_r
0,16,16:407723:G:A,407723,A,0.355244,-0.080704,0.011714,5.593560e-12,356446,0.401757,-0.150325,0.013207,5.108150e-30,0.330416
1,16,16:3708567:G:A,3708567,A,0.314140,0.066784,0.012033,2.852600e-08,359132,0.504393,0.113434,0.013187,7.859760e-18,-0.239183
2,16,16:4015729:C:T,4015729,T,0.384448,0.116658,0.011499,3.501560e-24,357924,0.344050,0.140383,0.011967,8.847040e-32,0.189035
3,16,16:4932470:G:A,4932470,A,0.437222,-0.068619,0.011281,1.179990e-09,357796,0.411542,-0.113932,0.012528,9.495070e-20,0.082282
4,16,16:9714809:A:AAGAG,9714809,AAGAG,0.299455,-0.070539,0.012237,8.194340e-09,356630,0.302316,-0.074659,0.012379,1.629130e-09,0.000000
5,16,16:19935763:G:A,19935763,A,0.139195,-0.125954,0.016128,5.728190e-15,359442,0.046126,-0.120769,0.016251,1.073950e-13,0.110538
6,16,16:20371075:A:T,20371075,T,0.484929,-0.072876,0.011142,6.133070e-11,361262,0.334864,-0.064084,0.011223,1.128610e-08,0.024450
7,16,16:24562458:T:C,24562458,C,0.483824,-0.062082,0.011161,2.659930e-08,360127,0.665335,-0.123614,0.012169,3.055450e-24,0.086424
8,16,16:24811740:T:C,24811740,C,0.266977,-0.081349,0.012596,1.056980e-10,360831,0.239018,-0.096410,0.012802,5.030740e-14,-0.068021
9,16,16:28334240:G:T,28334240,T,0.389775,-0.091392,0.011898,1.571860e-14,332718,0.416534,-0.072779,0.012573,7.102400e-09,-0.292801
10,16,16:28857645:A:G,28857645,G,0.405474,0.129342,0.011357,4.752350e-30,360219,0.349241,0.121326,0.011859,1.444330e-24,-0.063094
11,16,16:29994922:C:T,29994922,T,0.484633,0.126127,0.011189,1.802030e-29,358168,0.367412,0.155896,0.011486,5.811820e-42,0.171922
12,16,16:31075175:G:A,31075175,A,0.373145,-0.124927,0.011521,2.143150e-27,360753,0.345847,-0.202564,0.012750,7.736680e-57,0.000000
13,16,16:53807005:AT:A,53807005,A,0.482868,0.299494,0.011184,5.744520e-158,357994,0.525559,0.540461,0.022845,9.770000e-124,-0.325312
14,16,16:53814470:C:T,53814470,T,0.129047,-0.118643,0.016640,1.003460e-12,359974,0.100240,0.477231,0.028581,1.369720e-62,-0.426052
15,16,16:53815161:T:G,53815161,G,0.491533,0.279766,0.011137,2.926380e-139,360819,0.603834,0.941394,0.031817,2.136310e-192,0.532698
16,16,16:53815706:CTGTT:C,53815706,C,0.099094,-0.148509,0.018711,2.070780e-15,358414,0.293131,-1.424780,0.047526,1.838350e-197,-0.241786
17,16,16:53823745:T:G,53823745,G,0.110497,-0.130443,0.018495,1.753490e-12,333193,0.215455,-0.919497,0.040029,9.100680e-117,-0.310053
18,16,16:53828066:C:T,53828066,T,0.392165,0.349002,0.011405,1.224550e-205,360397,0.221446,-0.481828,0.030674,1.336110e-55,0.821113
19,16,16:53830491:T:C,53830491,C,0.432609,0.313572,0.011237,2.348400e-171,360693,0.291334,-0.329204,0.024414,1.934000e-41,-0.306611
20,16,16:53835825:C:T,53835825,T,0.062992,-0.148968,0.022975,8.930430e-11,359585,0.194289,-1.180670,0.046834,3.145320e-140,0.285448
21,16,16:53839355:GT:G,53839355,G,0.405865,0.122079,0.012224,1.747790e-23,310819,0.531150,0.171988,0.014993,1.843490e-30,-0.200972
22,16,16:53864764:CG:C,53864764,C,0.322651,-0.081399,0.012050,1.425430e-11,353039,0.168930,-0.086096,0.012545,6.732250e-12,0.000000
23,16,16:69144151:C:G,69144151,G,0.127241,0.094296,0.016732,1.744150e-08,360343,0.167532,0.100929,0.016795,1.860210e-09,-0.008063
24,16,16:69651866:C:T,69651866,T,0.409140,-0.106813,0.011354,5.071730e-21,359443,0.284944,-0.118653,0.011488,5.255390e-25,-0.005683
25,16,16:70514828:A:C,70514828,C,0.452027,0.079024,0.011236,2.017630e-12,358255,0.418530,0.082038,0.011278,3.480000e-13,-0.002181
26,16,16:72038659:C:T,72038659,T,0.322396,-0.069476,0.011944,5.996310e-09,359482,0.494010,-0.093545,0.012110,1.121790e-14,-0.019044
27,16,16:72993706:G:A,72993706,A,0.083896,-0.117671,0.020121,4.966680e-09,360055,0.027356,-0.120720,0.020186,2.227620e-09,-0.008788
28,16,16:73426890:C:T,73426890,T,0.081166,-0.112133,0.020547,4.828940e-08,355835,0.095447,-0.125442,0.020658,1.261690e-09,-0.032777
29,16,16:76702763:C:T,76702763,T,0.179811,0.081573,0.014544,2.038170e-08,359126,0.158147,0.084587,0.014564,6.325580e-09,0.000000

In [39]:
snps_only_chr16_all = chr16_all[~chr16_all["SNP"].isin(chr_16["SNP"])]
snps_only_chr16_all

,Chr,SNP,bp,refA,freq,b,se,p,n,freq_geno,bJ,bJ_se,pJ,LD_r
404,16,16:19926191:T:C,19926191,C,0.143032,-0.125751,0.015957,3.256410e-15,358927,0.052716,-0.117192,0.016100,3.359820e-13,0.128273
421,16,16:64697880:C:T,64697880,T,0.142307,-0.089371,0.015943,2.076990e-08,361088,0.178714,-0.098352,0.016293,1.574230e-09,-0.094547
424,16,16:69955690:A:G,69955690,G,0.440290,0.080898,0.011247,6.354120e-13,359348,0.475639,0.090583,0.012067,6.067540e-14,0.047963
427,16,16:72996162:G:A,72996162,A,0.399635,-0.065649,0.011515,1.191530e-08,352121,0.268171,-0.072136,0.011689,6.771440e-10,-0.007967
429,16,16:76697625:A:G,76697625,G,0.186761,0.078618,0.014359,4.372660e-08,357751,0.218650,0.086071,0.014425,2.418190e-09,0.000000

In [44]:
snps_only_chr16 = chr_16[~chr_16["SNP"].isin(chr16_all["SNP"])]
snps_only_chr16.shape

(4, 14)

In [43]:
common_snps = chr16_all[chr16_all["SNP"].isin(chr_16["SNP"])]
common_snps.shape

(26, 14)

In [34]:
common_snps = common_snps[["SNP", "bJ", "p"]]
common_snps.columns = ["SNP", "bJ", "p"]
common_snps

                     SNP        bJ              p
399        16:407723:G:A -0.150325   5.593560e-12
400       16:3708567:G:A  0.113434   2.852600e-08
401       16:4015729:C:T  0.140383   3.501560e-24
402       16:4932470:G:A -0.113932   1.179990e-09
403   16:9714809:A:AAGAG -0.074659   8.194340e-09
405      16:20371075:A:T -0.062074   6.133070e-11
406      16:24562458:T:C -0.121075   2.659930e-08
407      16:24811740:T:C -0.092689   1.056980e-10
408      16:28857645:A:G  0.138355   4.752350e-30
409      16:29994922:C:T  0.148511   1.802030e-29
410      16:31075175:G:A -0.206706   2.143150e-27
411     16:53807005:AT:A  0.540461  5.744520e-158
412      16:53814470:C:T  0.477231   1.003460e-12
413      16:53815161:T:G  0.941394  2.926380e-139
414  16:53815706:CTGTT:C -1.424780   2.070780e-15
415      16:53823745:T:G -0.919497   1.753490e-12
416      16:53828066:C:T -0.481828  1.224550e-205
417      16:53830491:T:C -0.329204  2.348400e-171
418      16:53835825:C:T -1.180670   8.930430e-11
419     16:53839355:GT:G  0.171988   1.747790e-23
420     16:53864764:CG:C -0.086096   1.425430e-11
422      16:69144151:C:G  0.105322   1.744150e-08
423      16:69651866:C:T -0.092882   5.071730e-21
425      16:70514828:A:C  0.078388   2.017630e-12
426      16:72038659:C:T -0.088867   5.996310e-09
428      16:73426890:C:T -0.134106   4.828940e-08

In [36]:
chr16_common = chr_16[chr_16["SNP"].isin(common_snps["SNP"])]
chr16_common = chr16_common[["SNP", "bJ", "p"]]
chr16_common.columns = ["SNP", "bJ", "p"]
chr16_common

                    SNP        bJ              p
0         16:407723:G:A -0.150325   5.593560e-12
1        16:3708567:G:A  0.113434   2.852600e-08
2        16:4015729:C:T  0.140383   3.501560e-24
3        16:4932470:G:A -0.113932   1.179990e-09
4    16:9714809:A:AAGAG -0.074659   8.194340e-09
6       16:20371075:A:T -0.064084   6.133070e-11
7       16:24562458:T:C -0.123614   2.659930e-08
8       16:24811740:T:C -0.096410   1.056980e-10
10      16:28857645:A:G  0.121326   4.752350e-30
11      16:29994922:C:T  0.155896   1.802030e-29
12      16:31075175:G:A -0.202564   2.143150e-27
13     16:53807005:AT:A  0.540461  5.744520e-158
14      16:53814470:C:T  0.477231   1.003460e-12
15      16:53815161:T:G  0.941394  2.926380e-139
16  16:53815706:CTGTT:C -1.424780   2.070780e-15
17      16:53823745:T:G -0.919497   1.753490e-12
18      16:53828066:C:T -0.481828  1.224550e-205
19      16:53830491:T:C -0.329204  2.348400e-171
20      16:53835825:C:T -1.180670   8.930430e-11
21     16:53839355:GT:G  0.171988   1.747790e-23
22     16:53864764:CG:C -0.086096   1.425430e-11
23      16:69144151:C:G  0.100929   1.744150e-08
24      16:69651866:C:T -0.118653   5.071730e-21
25      16:70514828:A:C  0.082038   2.017630e-12
26      16:72038659:C:T -0.093545   5.996310e-09
28      16:73426890:C:T -0.125442   4.828940e-08

In [37]:
comparison = pd.concat([common_snps.set_index("SNP"), chr16_common.set_index("SNP")], axis=1)

print("Common SNPs comparison:")
print(comparison)

Common SNPs comparison:
                           bJ              p        bJ              p
SNP
16:407723:G:A       -0.150325   5.593560e-12 -0.150325   5.593560e-12
16:3708567:G:A       0.113434   2.852600e-08  0.113434   2.852600e-08
16:4015729:C:T       0.140383   3.501560e-24  0.140383   3.501560e-24
16:4932470:G:A      -0.113932   1.179990e-09 -0.113932   1.179990e-09
16:9714809:A:AAGAG  -0.074659   8.194340e-09 -0.074659   8.194340e-09
16:20371075:A:T     -0.062074   6.133070e-11 -0.064084   6.133070e-11
16:24562458:T:C     -0.121075   2.659930e-08 -0.123614   2.659930e-08
16:24811740:T:C     -0.092689   1.056980e-10 -0.096410   1.056980e-10
16:28857645:A:G      0.138355   4.752350e-30  0.121326   4.752350e-30
16:29994922:C:T      0.148511   1.802030e-29  0.155896   1.802030e-29
16:31075175:G:A     -0.206706   2.143150e-27 -0.202564   2.143150e-27
16:53807005:AT:A     0.540461  5.744520e-158  0.540461  5.744520e-158
16:53814470:C:T      0.477231   1.003460e-12  0.477231   1.003460e-12
16:53815161:T:G      0.941394  2.926380e-139  0.941394  2.926380e-139
16:53815706:CTGTT:C -1.424780   2.070780e-15 -1.424780   2.070780e-15
16:53823745:T:G     -0.919497   1.753490e-12 -0.919497   1.753490e-12
16:53828066:C:T     -0.481828  1.224550e-205 -0.481828  1.224550e-205
16:53830491:T:C     -0.329204  2.348400e-171 -0.329204  2.348400e-171
16:53835825:C:T     -1.180670   8.930430e-11 -1.180670   8.930430e-11
16:53839355:GT:G     0.171988   1.747790e-23  0.171988   1.747790e-23
16:53864764:CG:C    -0.086096   1.425430e-11 -0.086096   1.425430e-11
16:69144151:C:G      0.105322   1.744150e-08  0.100929   1.744150e-08
16:69651866:C:T     -0.092882   5.071730e-21 -0.118653   5.071730e-21
16:70514828:A:C      0.078388   2.017630e-12  0.082038   2.017630e-12
16:72038659:C:T     -0.088867   5.996310e-09 -0.093545   5.996310e-09
16:73426890:C:T     -0.134106   4.828940e-08 -0.125442   4.828940e-08